# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from openelevationservice.server.grpc import openelevation_pb2 as openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2


class OpenElevationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PointElevation = channel.unary_unary(
                '/propagamap.OpenElevation/PointElevation',
                request_serializer=openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.LatLon.SerializeToString,
                response_deserializer=openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.Elevation.FromString,
                )
        self.LineElevation = channel.unary_unary(
                '/propagamap.OpenElevation/LineElevation',
                request_serializer=openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.LineRequest.SerializeToString,
                response_deserializer=openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.LineResponse.FromString,
                )
        self.AreaPointsElevation = channel.unary_unary(
                '/propagamap.OpenElevation/AreaPointsElevation',
                request_serializer=openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.AreaRequest.SerializeToString,
                response_deserializer=openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.AreaPointsResponse.FromString,
                )
        self.AreaRangesElevation = channel.unary_unary(
                '/propagamap.OpenElevation/AreaRangesElevation',
                request_serializer=openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.AreaRequest.SerializeToString,
                response_deserializer=openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.AreaRangesResponse.FromString,
                )


class OpenElevationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PointElevation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LineElevation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AreaPointsElevation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AreaRangesElevation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenElevationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PointElevation': grpc.unary_unary_rpc_method_handler(
                    servicer.PointElevation,
                    request_deserializer=openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.LatLon.FromString,
                    response_serializer=openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.Elevation.SerializeToString,
            ),
            'LineElevation': grpc.unary_unary_rpc_method_handler(
                    servicer.LineElevation,
                    request_deserializer=openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.LineRequest.FromString,
                    response_serializer=openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.LineResponse.SerializeToString,
            ),
            'AreaPointsElevation': grpc.unary_unary_rpc_method_handler(
                    servicer.AreaPointsElevation,
                    request_deserializer=openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.AreaRequest.FromString,
                    response_serializer=openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.AreaPointsResponse.SerializeToString,
            ),
            'AreaRangesElevation': grpc.unary_unary_rpc_method_handler(
                    servicer.AreaRangesElevation,
                    request_deserializer=openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.AreaRequest.FromString,
                    response_serializer=openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.AreaRangesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'propagamap.OpenElevation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OpenElevation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PointElevation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/propagamap.OpenElevation/PointElevation',
            openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.LatLon.SerializeToString,
            openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.Elevation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LineElevation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/propagamap.OpenElevation/LineElevation',
            openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.LineRequest.SerializeToString,
            openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.LineResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AreaPointsElevation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/propagamap.OpenElevation/AreaPointsElevation',
            openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.AreaRequest.SerializeToString,
            openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.AreaPointsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AreaRangesElevation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/propagamap.OpenElevation/AreaRangesElevation',
            openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.AreaRequest.SerializeToString,
            openelevationservice_dot_server_dot_grpc_dot_openelevation__pb2.AreaRangesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
