# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/propamap/v1/openelevation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(services/propamap/v1/openelevation.proto\x12\x14services.propamap.v1\"\"\n\x06LatLon\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\"\x1a\n\tElevation\x12\r\n\x05value\x18\x01 \x01(\x05\"e\n\x0bLineRequest\x12+\n\x05start\x18\x01 \x01(\x0b\x32\x1c.services.propamap.v1.LatLon\x12)\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x1c.services.propamap.v1.LatLon\">\n\x0fLatLonElevation\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x11\n\televation\x18\x03 \x01(\x05\"E\n\x0cLineResponse\x12\x35\n\x06points\x18\x01 \x03(\x0b\x32%.services.propamap.v1.LatLonElevation\"o\n\x0b\x41reaRequest\x12\x30\n\nbottomLeft\x18\x01 \x01(\x0b\x32\x1c.services.propamap.v1.LatLon\x12.\n\x08topRight\x18\x02 \x01(\x0b\x32\x1c.services.propamap.v1.LatLon\"K\n\x12\x41reaPointsResponse\x12\x35\n\x06points\x18\x01 \x03(\x0b\x32%.services.propamap.v1.LatLonElevation\":\n\nLineString\x12,\n\x06points\x18\x01 \x03(\x0b\x32\x1c.services.propamap.v1.LatLon\"<\n\x04\x41rea\x12\x34\n\nboundaries\x18\x01 \x03(\x0b\x32 .services.propamap.v1.LineString\"M\n\nUnitedArea\x12\x15\n\rbaseElevation\x18\x01 \x01(\x05\x12(\n\x04\x61rea\x18\x02 \x01(\x0b\x32\x1a.services.propamap.v1.Area\"r\n\x12\x41reaRangesResponse\x12\x30\n\x06unions\x18\x01 \x03(\x0b\x32 .services.propamap.v1.UnitedArea\x12\x14\n\x0cminElevation\x18\x02 \x01(\x05\x12\x14\n\x0cmaxElevation\x18\x03 \x01(\x05\x32\x80\x03\n\rOpenElevation\x12O\n\x0ePointElevation\x12\x1c.services.propamap.v1.LatLon\x1a\x1f.services.propamap.v1.Elevation\x12V\n\rLineElevation\x12!.services.propamap.v1.LineRequest\x1a\".services.propamap.v1.LineResponse\x12\x62\n\x13\x41reaPointsElevation\x12!.services.propamap.v1.AreaRequest\x1a(.services.propamap.v1.AreaPointsResponse\x12\x62\n\x13\x41reaRangesElevation\x12!.services.propamap.v1.AreaRequest\x1a(.services.propamap.v1.AreaRangesResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.propamap.v1.openelevation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LATLON._serialized_start=66
  _LATLON._serialized_end=100
  _ELEVATION._serialized_start=102
  _ELEVATION._serialized_end=128
  _LINEREQUEST._serialized_start=130
  _LINEREQUEST._serialized_end=231
  _LATLONELEVATION._serialized_start=233
  _LATLONELEVATION._serialized_end=295
  _LINERESPONSE._serialized_start=297
  _LINERESPONSE._serialized_end=366
  _AREAREQUEST._serialized_start=368
  _AREAREQUEST._serialized_end=479
  _AREAPOINTSRESPONSE._serialized_start=481
  _AREAPOINTSRESPONSE._serialized_end=556
  _LINESTRING._serialized_start=558
  _LINESTRING._serialized_end=616
  _AREA._serialized_start=618
  _AREA._serialized_end=678
  _UNITEDAREA._serialized_start=680
  _UNITEDAREA._serialized_end=757
  _AREARANGESRESPONSE._serialized_start=759
  _AREARANGESRESPONSE._serialized_end=873
  _OPENELEVATION._serialized_start=876
  _OPENELEVATION._serialized_end=1260
# @@protoc_insertion_point(module_scope)
