---
attribution: "service by https://openrouteservice.org | data by http://srtm.csi.cgiar.org"
coord_precision: 0.000833333333
maximum_nodes: 2000
srtm_parameters:
  user: user
  password: pw
provider_parameters:
  table_name: oes_cgiar
  db_name: gis
  user_name: docker
  password: docker
  host: 192.168.71.37
  port: 49153
