name: Production Docker Image CI/CD

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      release-version: ${{ steps.pre-step.outputs.release-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: pre-step
        shell: bash
        run: echo "release-version=$(echo ${GITHUB_REF:10})" >> $GITHUB_OUTPUT
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.pre-step.outputs.release-version }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Invoke deployment hook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.PRODUCTION_WEBHOOK_URL }}?tag=${{ needs.build.outputs.release-version }}
          insecure: true
